version: "3.9"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: stegosec/tricera-lite-web:0.1.0
    environment:
      - API_BASE_URL=http://api:8080
    ports:
      - "8000:8000"
    depends_on: [api]
    read_only: true
    tmpfs: ["/tmp"]
    security_opt: ["no-new-privileges:true"]
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: stegosec/tricera-lite-api:0.1.0
    environment:
      - SCANNER_URL=http://scanner:8090
      - MAX_FILE_BYTES=5242880       # <-- corregido
      - LITE_MODE=true
    expose: ["8080"]
    depends_on: [scanner]
    read_only: true
    tmpfs: ["/tmp"]
    security_opt: ["no-new-privileges:true"]
    restart: unless-stopped

  scanner:
    build:
      context: ./scanner
      dockerfile: Dockerfile
    image: stegosec/tricera-lite-scanner:0.1.0
    environment:
      - RULES_PATH=/app/rules/fortinet_baseline.yml   # <-- corregido
    expose: ["8090"]
    read_only: true
    tmpfs: ["/tmp"]
    security_opt: ["no-new-privileges:true"]
    restart: unless-stopped

